### ISSUE TITLE
RequestError: Error: socket hang up

### ISSUE THREAD

**Issue by iandronowicz** [bram-is/homebridge-slide-shutter#10]
Everything was working fine until a couple of days ago when it stopped. Checking the logs I found this:

[11/12/2022, 1:42:31 AM] [slide-shutter] RequestError: Error: socket hang up
    at new RequestError (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnEnd (node:_http_client:512:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  cause: Error: socket hang up
      at connResetException (node:internal/errors:711:14)
      at Socket.socketOnEnd (node:_http_client:512:23)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  },
  error: Error: socket hang up
      at connResetException (node:internal/errors:711:14)
      at Socket.socketOnEnd (node:_http_client:512:23)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  },
  options: {
    uri: 'http://--------/rpc/Slide.GetInfo',
    method: 'GET',
    timeout: 6000,
    headers: { 'User-Agent': 'homebridge-slide-link' },
    json: true,
    auth: {
      username: 'user',
      password: '--------',
      sendImmediately: false,
      user: 'user',
      pass: '------'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by bramsmulders** [comment]
Hi @iandronowicz, 

thanks for your detailed error message. On first glance it looks like an connection problem, does your curtain have a static IP address?

**Comment by bramsmulders** [comment]
Closed due to no response
