### ISSUE TITLE
Local connection not working

### ISSUE THREAD

**Issue by blb4github** [bram-is/homebridge-slide-shutter#8]
**Describe Your Problem:**
Hi Bram, first of all thanks for this plugin! I have just installed; remote API is working, but local isn't. Should it work "out of the box" or is it required to request an update from IIM? Or something else required?

**Logs:**

```
6/1/2021, 10:38:06 PM] [slide-curtains] RequestError: Error: connect ECONNREFUSED 172.31.0.60:80
    at new RequestError (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.onRequestError (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:388:22)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  cause: Error: connect ECONNREFUSED 172.31.0.60:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.31.0.60',
    port: 80
  },
  error: Error: connect ECONNREFUSED 172.31.0.60:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.31.0.60',
    port: 80
  },
  options: {
    uri: 'http://172.31.0.60/rpc/Slide.GetInfo',
    method: 'GET',
    timeout: 6000,
    headers: { 'User-Agent': 'homebridge-slide-link' },
    json: true,
    auth: {
      username: 'user',
      password: 'xxxxxxxx',
      sendImmediately: false,
      user: 'user',
      pass: 'xxxxxxxx'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
[6/1/2021, 10:38:16 PM] [slide-curtains] RequestError: Error: connect ECONNREFUSED 172.31.0.61:80
    at new RequestError (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.onRequestError (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:388:22)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  cause: Error: connect ECONNREFUSED 172.31.0.61:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.31.0.61',
    port: 80
  },
  error: Error: connect ECONNREFUSED 172.31.0.61:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.31.0.61',
    port: 80
  },
  options: {
    uri: 'http://172.31.0.61/rpc/Slide.GetInfo',
    method: 'GET',
    timeout: 6000,
    headers: { 'User-Agent': 'homebridge-slide-link' },
    json: true,
    auth: {
      username: 'user',
      password: 'xxxxxxxx',
      sendImmediately: false,
      user: 'user',
      pass: 'xxxxxxxx'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
[6/1/2021, 10:38:16 PM] [slide-curtains] RequestError: Error: connect ECONNREFUSED 172.31.0.60:80
    at new RequestError (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.onRequestError (/homebridge/node_modules/homebridge-slide-shutter/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:388:22)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  cause: Error: connect ECONNREFUSED 172.31.0.60:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.31.0.60',
    port: 80
  },
  error: Error: connect ECONNREFUSED 172.31.0.60:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.31.0.60',
    port: 80
  },
  options: {
    uri: 'http://172.31.0.60/rpc/Slide.GetInfo',
    method: 'GET',
    timeout: 6000,
    headers: { 'User-Agent': 'homebridge-slide-link' },
    json: true,
    auth: {
      username: 'user',
      password: 'xxxxxxxx',
      sendImmediately: false,
      user: 'user',
      pass: 'xxxxxxxx'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

```

**Plugin Config:**

```json
"name": "slide-curtains",
            "tolerance": 5,
            "pollInterval": 30,
            "remote": true,
            "username": "xxx@xxxx.nl",
            "password": "xxxxxxx",
            "devices": [
                {
                    "name": "Voorkamer",
                    "ip": "172.31.0.61",
                    "code": "xxxxxxxx",
                    "pollInterval": 10
                },
                {
                    "name": "Achterkamer",
                    "ip": "172.31.0.60",
                    "code": "xxxxxxxx",
                    "pollInterval": 10
                }
            ],
            "platform": "slide-shutter"
        }
```

**Screenshots:**

**Environment:**

Latest Homebridge in Docker on Qnap nas

**Comment by bramsmulders** [comment]
Hi @blb4github, sorry for my late response! 

By default a slide curtain motor is only enabled for the remote API. Local API is currently in beta and you can request beta access by sending a mail to Slide support. After they enabled beta access you can toggle between local and remote by pressing the reset button 2 times shortly after eachother. 

I hope i've given you enough information to continue, if not feel free to respond to this ticket.

**Comment by blb4github** [comment]
Hi Bram,

mand sorry I didn’t update already it’s working already with local API. I did reach out to IIM support and they provided the required info.

**Comment by bramsmulders** [comment]
Thank you for your response, I'm glad it all worked out for you!
