### ISSUE TITLE
Freeze at "opening..." tile

### ISSUE THREAD

**Issue by iandronowicz** [bram-is/homebridge-slide-shutter#9]
Not always but a few times when opening the curtain the tile hangs at the "opening..." loading icon and won't go to "open" status

It should show the tile status as "open" when the curtain finishes opening.

**Comment by iandronowicz** [comment]
this is the error log:

[11/22/2021, 9:10:04 PM] [slide-shutter] RequestError: Error: ETIMEDOUT
    at new RequestError (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request/request.js:851:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  cause: Error: ETIMEDOUT
      at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ETIMEDOUT',
    connect: true
  },
  error: Error: ETIMEDOUT
      at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-slide-shutter/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ETIMEDOUT',
    connect: true
  },
  options: {
    uri: 'http://10.0.1.128/rpc/Slide.GetInfo',
    method: 'GET',
    timeout: 6000,
    headers: { 'User-Agent': 'homebridge-slide-link' },
    json: true,
    auth: {
      username: 'user',
      password: 'xxxxxxxx',
      sendImmediately: false,
      user: 'user',
      pass: 'xxxxxxxx'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by iandronowicz** [comment]
![image](https://user-images.githubusercontent.com/250746/143227061-8e00fe82-2e5c-400f-87f0-6e3639c51207.jpeg)

**Comment by bramsmulders** [comment]
Hi @iandronowicz! thnx for your bug report. 
from the bug report I can see that your Slide is not accessible from the network. Make sure that your slide has an assigned IP address, and then try and reboot your Slide or reboot your router to solve the problem. 

For the hanging "Open..." state, this happens sometimes after a couple of weeks/months of usage. The problem lies within the Slide motor which cannot pull the curtains to fully open state anymore. The plugin has a `tolerance` setting for a theshold in % to still consider state fully open or fully closed. This defaults to 5%. Which means that homekit will consider the curtain "Open" even if the Slide motor is only able to open the curtains till lets say 98%. 

There are 2 possible solutions: 
- Increase `tolerance` setting on your curtain to a percentage that works for you. 
- Recalibrate the slide curtain, so you teach your Slide to open to 100% again. (see steps below how to do this)

**Recalibrate Slide**
_Local slides_
Do a POST request to `YOUR-SLIDE-IP/rpc/Slide.Calibrate`. Your Slide will open and close again to recalibrate itself. 
You can use https://postman.com to do the post request from your computer. 

_Remote slides_
From the app you can recalibrate each slide.

**Comment by bramsmulders** [comment]
I'm going to close this issue, if you still have problems feel free to re-open it.
